services:
  airflow:
    build:
      context: ..
      dockerfile: infra/Dockerfile.airflow
    command: airflow standalone
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - _AIRFLOW_DB_MIGRATE=true
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=true  
      - PYTHONPATH=/app
    volumes:
      - ./airflow/dags/:/opt/airflow/dags  
      - ../:/app
    healthcheck:
      test: wget http://localhost:8080/api/v2/monitor/health -o /dev/null || exit 1  
      retries: 3
      interval: 5s
