services:
  tests:
    build:
      context: ..
      dockerfile: infra/Dockerfile.dev
    container_name: taxi-ml-tests
    environment:
      ENV: test
      PYTHONPATH: /app
    volumes:
      - ../:/app
    working_dir: /app
    command: pytest tests -q
