environment: prod

paths:
  project_dir: /app
  data: /app/data
  raw: /app/data/raw/5000mini_train.csv
  preprocessed: /app/data/preprocessed/
  features: /app/data/features/
  models: /app/models
  model: /app/models/logreg_bundle.joblib
  artefacts: /app/artefacts
  graph_artefact: /app/artefacts/train_graph.json

api:
  host: 0.0.0.0
  port: 8000
